# Generated by Django 4.0.6 on 2023-01-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pais', models.CharField(max_length=30)),
                ('moeda_local', models.CharField(max_length=30)),
                ('adicionada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
